language: python
python:
  - "3.10-dev"
install:
  - pip install -r requirements.txt
  - python manage.py migrate
script:
  - black --check blogging mysite polling # Add this line
  - python manage.py test